[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 1
via_ir = true
solc_version = "0.8.30"
evm_version = "prague"

# Fork testing configuration
[rpc_endpoints]
polygon = "${NODE_URL_137}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
